name: 'Run Tests'
description: 'Execute Raptoreum unit tests'
inputs:
  platform:
    description: 'Platform identifier for test reports'
    required: true
  version:
    description: 'Version string'
    required: true
  coin-name:
    description: 'Coin name'
    required: false
    default: 'raptoreum'

runs:
  using: "composite"
  steps:
    - name: Run Unit Tests
      id: tests
      shell: bash
      run: |
        chmod +x test_raptoreum
        ./test_raptoreum --log_format=JUNIT > unit_test_results.xml

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.coin-name }}-${{ inputs.platform }}-test-results-${{ inputs.version }}
        path: unit_test_results.xml

    - name: Publish Unit Test Report
      uses: mikepenz/action-junit-report@v5
      if: always()
      with:
        check_name: ${{ inputs.platform }}
        detailed_summary: ${{ steps.tests.conclusion == 'failure' }}
        include_passed: false
        report_paths: unit_test_results.xml

